# Dependencies
highlighter:          rouge
markdown:             kramdown 

# Permalinks
permalink:            pretty

# Setup
title:                majug
tagline:              'Mannheim Java User Group'
description:          'Community der Java Anwender in Mannheim und Rhein Neckar Dreieck'
url:                  http://majug.de
baseurl:              /
events_baseurl:       /events/

author:
  name:               'majug'
  url:                http://majug.de
  twitter:            https://twitter.com/majug

paginate:             5
paginate_path:        '/events/page:num'

# Custom vars
version:              2.1.0

github:
  repo:               https://github.com/majug/majug.github.io
